version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run build && npm run start"
    networks:
      - my-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      - my-network
networks:
  my-network:
